#!/usr/bin/env zsh

if command -v surf >/dev/null
then
    BROWSER=surf
elif [ "$(uname -s)" = Darwin ]
then
    BROWSER=open
else
    BROWSER=firefox
fi

GPG_TTY=$(tty)
FREETYPE_PROPERTIES="truetype:interpreter-version=35"
LANG='en_US.UTF-8'
LESS='-g -i -M -R -w -z-4 -F -X'
LESSOPEN='|lesspreprocess %s'
PAGER='less'
SHELL="$(which zsh)"
TMPPREFIX="$TMPDIR/zsh"

EDITOR='nvim'
VISUAL="$EDITOR"

PYTHONSTARTUP=~/.pythonrc
HUSKY_SKIP_HOOKS='true'

XDG_CONFIG_HOME="$HOME/.config"
XDG_DATA_HOME="$HOME/.local/share"

ANSIBLE_CONFIG=$XDG_CONFIG_HOME/ansible.cfg
CLASSPATH="$HOME/workspace/libs"
GOROOT="/usr/local/go"
GOPATH="$HOME/go"
N_PREFIX="$HOME/.local"
NVM_DIR="$XDG_CONFIG_HOME/nvm"
PACKER_CACHE_DIR="$XDG_DATA_HOME/packer_cache"
PACKER_CONFIG_DIR="$XDG_CONFIG_HOME/packer/config"
PACKER_HOME_DIR="$XDG_CONFIG_HOME/packer"
PYENV_ROOT="$XDG_CONFIG_HOME/pyenv"
RANCHER_ROOT="$HOME/.rd"
RBENV_ROOT="$XDG_CONFIG_HOME/rbenv"
VAGRANT_HOME="$XDG_CONFIG_HOME/.vagrant.d"
WINEPREFIX="$XDG_CONFIG_HOME/wine"
ZDOTDIR="$XDG_CONFIG_HOME/zsh"
Z_DIR="$XDG_CONFIG_HOME/z"

# TODO Clean up
LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/opt/openssl@3/lib"
AWS_SDK_LOAD_CONFIG=true

path=(
    /usr/local/bin
    /usr/local/sbin
    $path
)

if [ "$(uname -s)" = Darwin ]
then
    path=(
        /Applications/Postgres.app/Contents/Versions/14/bin
        /opt/homebrew/opt/findutils/libexec/gnubin
        /opt/homebrew/opt/gnu-sed/libexec/gnubin
        /opt/homebrew/opt/openssl@3/bin
        /opt/homebrew/bin
        /opt/homebrew/sbin
        $path
    )
fi

path=(
    $HOME/bin
    $HOME/.local/bin
    $GOROOT/bin
    $PYENV_ROOT/bin
    $RBENV_ROOT/bin
    $HOME/.tfenv/bin
    $HOME/.cargo/bin
    $RANCHER_ROOT/bin
    $path
)

if [ ! -d "$TMPDIR" ]
then
    TMPDIR="$XDG_DATA_HOME/tmp"
    mkdir -p "$TMPDIR"
    chmod 700 "$TMPDIR"
fi

export \
    ANSIBLE_CONFIG \
    BROWSER \
    CLASSPATH \
    EDITOR \
    FREETYPE_PROPERTIES \
    GOPATH \
    GOROOT \
    LANG \
    LESS \
    LESSOPEN \
    N_PREFIX \
    NVM_DIR \
    PAGER \
    PYENV_ROOT \
    PYTHONSTARTUP \
    RBENV_ROOT \
    TMPDIR \
    TMPPREFIX \
    VAGRANT_HOME \
    VISUAL \
    WINEPREFIX \
    XDG_CONFIG_HOME \
    XDG_DATA_HOME \
    ZDOTDIR \
    Z_DIR \
    path \
    LIBRARY_PATH \
    AWS_SDK_LOAD_CONFIG \
    GPG_TTY \
