#!/usr/bin/env zsh

if command -v surf >/dev/null
then
    BROWSER=surf
elif [ "$(uname -s)" = Darwin ]
then
    BROWSER=open
else
    BROWSER=firefox
fi

XDG_CONFIG_HOME="$HOME/.config"
XDG_DATA_HOME="$HOME/.local/share"

ANSIBLE_CALLBACK_WHITELIST=profile_tasks
ANSIBLE_FORCE_COLOR=true
ANSIBLE_LOAD_CALLBACK_PLUGINS=1
ANSIBLE_STDOUT_CALLBACK=yaml
CLASSPATH="$HOME/workspace/libs"
EDITOR='vim'
GOPATH="$HOME/go"
LANG='en_US.UTF-8'
LESS='-g -i -M -R -w -z-4 -F -X'
LESSOPEN='|lesspreprocess %s'
N_PREFIX="$HOME/.local"
PACKER_CACHE_DIR="$XDG_DATA_HOME/packer_cache"
PACKER_CONFIG_DIR="$XDG_CONFIG_HOME/packer/config"
PACKER_HOME_DIR="$XDG_CONFIG_HOME/packer"
PAGER='less'
PYENV_ROOT="$XDG_CONFIG_HOME/pyenv"
PYTHONSTARTUP=~/.pythonrc
RBENV_ROOT="$XDG_CONFIG_HOME/rbenv"
TMPPREFIX="$TMPDIR/zsh"
VAGRANT_HOME="$XDG_CONFIG_HOME/.vagrant.d"
VISUAL="$EDITOR"
ZDOTDIR="$XDG_CONFIG_HOME/zsh"
Z_DIR="$XDG_CONFIG_HOME/z"

path=(
    $HOME/bin
    $HOME/.local/bin
    $HOME/go/bin
    $HOME/.tfenv/bin
    $HOME/.cargo/bin
    $PYENV_ROOT/bin
    $RBENV_ROOT/bin
    /usr/local/sbin
    $path
)

if [ ! -d "$TMPDIR" ]
then
    TMPDIR="$XDG_DATA_HOME/tmp"
    mkdir -p "$TMPDIR"
    chmod 700 "$TMPDIR"
fi

export \
    ANSIBLE_CALLBACK_WHITELIST \
    ANSIBLE_FORCE_COLOR \
    ANSIBLE_LOAD_CALLBACK_PLUGINS \
    ANSIBLE_STDOUT_CALLBACK \
    BROWSER \
    CLASSPATH \
    EDITOR \
    GOPATH \
    LANG \
    LESS \
    LESSOPEN \
    N_PREFIX \
    PAGER \
    PYENV_ROOT \
    PYTHONSTARTUP \
    RBENV_ROOT \
    TMPDIR \
    TMPPREFIX \
    VAGRANT_HOME \
    VISUAL \
    XDG_CONFIG_HOME \
    XDG_DATA_HOME \
    ZDOTDIR \
    Z_DIR \
    path \
