#!/usr/bin/env zsh
if [ "$(uname -s)" = 'Darwin' ]
then
    brew_fpath=$(brew --prefix)/share/zsh-completions
    brew_fpath2=$(brew --prefix)/share/zsh/site-functions/
    if ! [[ -d $brew_fpath ]]
    then
        echo "Installing zsh-completions..."
        brew install zsh-completions
    fi
    fpath=(
        $brew_fpath
        $brew_fpath2
        $fpath
    )
fi

fpath=(
  "$XDG_CONFIG_HOME/zsh/completions"
  $fpath
)
