#!/usr/bin/env zsh
# Misc
alias edot='dot -Tpng | feh --scale-down -'
alias .z='TASKS=1 . "${ZDOTDIR}"/.zshrc'
alias agrep='alias | grep'
alias allow='sudo xattr -d -r com.apple.quarantine'
alias fuck='sudo $(fc -ln -1)'
alias ish='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias sshr='ssh-keygen -R'
alias sshe='ssh -O exit'
alias ussh='try_ssh_forever'
alias vim='nvim'

# From files
for f in "$ZDOTDIR"/aliases/*; do . "$f"; done

[ -d "$XDG_CONFIG_HOME/shell_aliases" ] && \
    for f in "$XDG_CONFIG_HOME"/shell_aliases/*; do . "$f"; done

try_ssh_forever () {
    until ssh $@; do printf '\33[2K\33[A'; done
}

add-brew-bin-to-path () {
    paths=(/usr/local/Cellar/"$1"/*)
    if [ "${#paths}" -eq 1 ]
    then
        path=("${paths[1]}/libexec/gnubin" $path)
    elif [ "${#paths}" -gt 1 ]
    then
        path=("${paths[1]}/libexec/gnubin" $path)
    else
        echo "No $1 found in Cellar." >&2
    fi
    export path
}

use-gnu-tools () {
    add-brew-bin-to-path 'gnu-sed'
    add-brew-bin-to-path 'coreutils'
}

realpath () {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

colors () {
    for i in {0..255}
    do
        printf "\x1b[38;5;${i}m${i}\n"
    done
}

git_recent_branches () {
    git reflog \
    | sed -En 's/.*moving from ([^ ]*) to ([^$]*)/\1\
\2/p' \
    | head "-${1:-100}" \
    | sort -u
}

agent () {
    eval `ssh-agent -s`
    ssh-add
}

brew () {
    env PATH=${PATH//$(pyenv root)\/shims:/} brew "$@"
}

used_git_aliases () {
    history 0 | awk '/\w*[0-9]*  g/ && !/(grep|awk|grub|ghc|groups|gem|pass|git|gpg|gdb)/ {print $2}' | sort -u
}

alias | grep gpa &>/dev/null && unalias gpa

signit () {
    file="$1"
	if [[ -z "$file" ]]
	then
		echo "Provide a filename and try again."
	else
		target_dts=$(date -d "$(stat -c %Y $file | awk '{print strftime("%c",$1)}')" +%Y%m%d%H%M.%S)
        gpg --detach-sign "$file"
        touch -t "$target_dts" "$file.sig"
	fi
}
