#!/usr/bin/env zsh
export CLASSPATH="$HOME/workspace/libs"
export LANG='en_US.UTF-8'
export LESS='-g -i -M -R -S -w -z-4 -F -X'
export LESSOPEN='|lesspreprocess %s'
export PAGER='less'
export PYTHONSTARTUP=~/.pythonrc
export VISUAL="$EDITOR"

export VAGRANT_HOME="$XDG_CONFIG_HOME/.vagrant.d"
export Z_DIR="$XDG_CONFIG_HOME/z"
export NVM_DIR="$XDG_CONFIG_HOME/nvm"
export PYENV_ROOT="$XDG_CONFIG_HOME/pyenv"
export RBENV_ROOT="$XDG_CONFIG_HOME/rbenv"
export GOPATH="$HOME/go"

path=(
  "$PYENV_ROOT/bin"
  "$RBENV_ROOT/bin"
  /opt/terminus/bin
  $path
)
fpath=(
  "$XDG_CONFIG_HOME/zsh-completions"
  $fpath
)

export path fpath

case "$OSTYPE" in
    linux*) true;;
    darwin*) export BROWSER='open';;
esac
