alias tf='terraform'
alias tfp='terraform plan'
alias tfa='terraform apply'
alias tff='terraform fmt'
alias tfim='terraform import'
alias tfin='terraform init'

alias tg='terragrunt'
alias tgp='terragrunt plan'
alias tga='terragrunt apply'
alias tgf='terragrunt fmt'
alias tgim='terragrunt import'
alias tgin='terragrunt init'
