#!/usr/bin/env zsh
#compdef gimme-aws-creds
#autoload

_gimme-aws-creds() {
    _arguments '-p+[AWS Profiles]:Profiles:->profiles'
    case "$state" in
        (profiles) _profiles ;;
    esac
}

_profiles() {
    local IFS cache_identifier profiles
    cache_identifier='gimme-aws-creds_all_profiles'
    IFS=$'\n'
    if ! _retrieve_cache "$cache_identifier"
    then
        profiles=($(gimme-aws-creds --list-profiles | sed -En 's/\[(.+)\]/\1/p'))
        _store_cache "$cache_identifier" profiles
    fi
    _values 'Profiles' $profiles
}

_gimme-aws-creds
